### ISSUE TITLE
启动时报错

### ISSUE THREAD

**Issue by fanyuxing20** [Agnes4m/nonebot_plugin_poke#5]
日志：
```
07-30 10:23:13 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_autohelp"
07-30 10:23:13 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_weather_lite"
07-30 10:23:13 [ERROR] nonebot | Failed to import "nonebot_plugin_poke"
Traceback (most recent call last):
  File "F:\portfolio\qqbot\bot.py", line 24, in <module>
    nonebot.load_from_toml("pyproject.toml", encoding="utf-8")
  File "F:\miniconda3\envs\qqbot\lib\site-packages\nonebot\plugin\load.py", line 130, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "F:\miniconda3\envs\qqbot\lib\site-packages\nonebot\plugin\load.py", line 64, in load_all_plugins
    return manager.load_all_plugins()
  File "F:\miniconda3\envs\qqbot\lib\site-packages\nonebot\plugin\manager.py", line 176, in load_all_plugins
    return set(
  File "F:\miniconda3\envs\qqbot\lib\site-packages\nonebot\plugin\manager.py", line 177, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "F:\miniconda3\envs\qqbot\lib\site-packages\nonebot\plugin\manager.py", line 142, in load_plugin
    module = importlib.import_module(name)
  File "F:\miniconda3\envs\qqbot\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "F:\miniconda3\envs\qqbot\lib\site-packages\nonebot\plugin\manager.py", line 242, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\miniconda3\envs\qqbot\lib\site-packages\nonebot_plugin_poke\__init__.py", line 12, in <module>
    from .utils import *
  File "F:\miniconda3\envs\qqbot\lib\site-packages\nonebot_plugin_poke\utils.py", line 6, in <module>
    import aiohttp
ModuleNotFoundError: No module named 'aiohttp'
```

**Comment by Agnes4m** [comment]
已修复，更新v0.1.1
